# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Execute app.py

on:
  workflow_dispatch:
    inputs:
      logLevel:
      description: 'Log level'
      required: true
      default: 'debug'
      type: choice
      options:
      - info
      - warning
      - debug
  schedule:
    - cron: '0 23 * * *'  # every full hour

jobs:
  build:
    runs-on: ubuntu-latest
    environment: default
    steps:
    - uses: actions/checkout@v2
      with:
        ref: workflow
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run app.py
      #env:
        #NC_USER: ${{ secrets.NC_USER }}
      run: |
        python app.py -t -d 2022-02-01,2023-02-04 
