# This workflow will install Python dependencies, run tests and lint with a single version of Python.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Execute app.py

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: '- log info'
        type: choice
        options:
        - -log info
        - -log warning
        - -log debug
      test:
        description: 'Test Run Flag'
        required: false
        default: ' '
        type: choice
        options:
        - ' '
        - '-t'
  #schedule:
  #  - cron: '0 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Set start date
      run: echo "START_DATE=$(date -d '-60 day' +'%Y-%m-%d')" >> $GITHUB_ENV
    - name: Run app.py
      env:
        SEVDESK_API_KEY: ${{ secrets.SEVDESK_API_KEY }}
        EASYBILL_API_KEY: ${{ secrets.EASYBILL_API_KEY }}
      run: |
        python app.py -d $START_DATE,2030-12-30 ${{ github.event.inputs.logLevel }} ${{ github.event.inputs.test }}
